### ISSUE TITLE
User Testing "enhancement"

### ISSUE THREAD

**Issue by InassTubail** [FACG5/CHariZone#153]
* Add logo for each charity.
* Change color palate.
* Change Fonts.
* Add donate button in (profile / search page / category page) :under constructions. 
* Try to animate menu burger.
* How it works section (donate, search and compare).
* Edit list of categories with its icons "slider"  : (Medical Research | Animals | Children | Hospitals & Hospices | Overseas Aid and Relief | Education | General | Homelessness | Disability | Environment).
* Advance search: remove by expenditure, income by range.(Done)
* Refactor design as want in user tesing documents (category/search page).
* Add comparison button in the profile page. 
* Add comparison in the category page.
* Maybe not make hover in a logo in the search page which contains overall charity KPI.

**Comment by InassTubail** [comment]
But we don't know what do you meant by sort button in the category page " do you want to filter results as we make in an advanced search.

**Comment by InassTubail** [comment]
Also, how we can calculate the overall value to "financial, governance& impact " in the home tab in comparison page.

**Comment by InassTubail** [comment]
Are you really want to change red, grey and green Flags "natural, positive and negative" into circular indicators?
Then will be no indicators box ??!

**Comment by SGams** [comment]
>           Are you really want to change red, grey and green Flags "natural, positive and negative" into circular indicators?
> Then will be no indicators box ??!

it's neutral - not natural. 
yes please - but I don't know what you mean by indicator boxes?

**Comment by SGams** [comment]
>           But we don't know what do you meant by sort button in the category page " do you want to filter results as we make in an advanced search.

with that I just mean arrange the results search by size (income)

**Comment by InassTubail** [comment]
> with that I just mean arrange the results search by size (income)

If we have time we will work on sort feature in category page

**Comment by InassTubail** [comment]
> > ```
> >       Are you really want to change red, grey and green Flags "natural, positive and negative" into circular indicators?
> > ```
> > Then will be no indicators box ??!
> 
> it's neutral - not natural.
> yes please - but I don't know what you mean by indicator boxes?

when we made a vedio call on Thursday, We agreed on making box that indicates user that  what red,green and grey falgs mean, But you are want to change Flag symbol  to a circular shape inside it "neutral ,positive and negative" keyword.

**Comment by InassTubail** [comment]
> Inas, will you also change the comparison page and the charity insight page for the new design I am suggesting?
Sure , We will refactor design as want in user tesing documents (category/search page).

**Comment by SGams** [comment]
I am much more interested in the comparison page and the charity insight page - would they be changed according to the document ? or something close ?

**Comment by SGams** [comment]
Inas, will you also change the comparison page and the charity insight page for the new design I am suggesting?
Sure , We will refactor design as want in user tesing documents (category/search page).

----I am much more interested in the comparison page and the charity insight page - would they be changed according to the document ? or something close ?

**Comment by SGams** [comment]
>Can you confirm that you will change the comparison page and the 
>charity insight page ? they are the key pages
>
s
>
>
>
>
Best,
Sarah

------ Original Message ------

**Comment by SGams** [comment]
I thought it we add the pie chart with the label (neurtal, positive, 
negative) it would save us from doing the box ( and more space)



Best,
Sarah

------ Original Message ------

**Comment by SGams** [comment]
That's fine - thanks

Best,
Sarah

------ Original Message ------
